spring:
  application:
    name: resume-builder-backend

  datasource:
    url: jdbc:mysql://localhost:3306/resume_builder?useSSL=false&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: dGhpc0lzQVZlcnlMb25nU3VwZXJTZWNyZXRLZXlGb3JKV1RTaWduaW5nMjAyNg==
    expiration-ms: 86400000

  oauth2:
    authorized-redirect-uri: http://localhost:5173/auth/callback

logging:
  level:
    org.springframework.security: INFO
